name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Rodar testes
        run: |
          echo "Aqui você pode rodar testes automatizados, linter, etc"
