name: Deploy Node.js no Raspberry

on:
  push:
    branches:
      - main  # ou a branch que você usar

jobs:
  deploy:
    runs-on: self-hosted  # importante: indica que será executado no Raspberry
    steps:
      - name: Atualizar projeto local
        run: |
          cd ~/Documentos/wsp/nativo_wpp_scrapping
          git pull origin main

      - name: Instalar dependências
        run: |
          cd ~/Documentos/wsp/nativo_wpp_scrapping
          npm install

      - name: Reiniciar app com PM2
        run: |
          cd ~/Documentos/wsp/nativo_wpp_scrapping
          ./start.sh
